=== stming/nics-teamsite/TeamSite/classes/src/dbunit/Nikon-BV-DBSchema.dtd
<!ELEMENT dataset (
    ACCESSORY*,
    ACCESSORY_2_AWARD*,
    ACCESSORY_2_CATEGORY*,
    ACCESSORY_2_COUNTRY*,
    ACCESSORY_2_KIT*,
    ACCESSORY_2_PRODUCT*,
    AWARD*,
    AWARD_2_COUNTRY*,
    BILL_OF_MATERIALS*,
    CATEGORY*,
    COLOUR_WAY*,
    COUNTRY*,
    COUNTRY_LANGUAGE*,
    DCR*,
    IMAGE*,
    KIT*,
    KIT_2_AWARD*,
    KIT_2_CATEGORY*,
    KIT_2_COUNTRY*,
    LANGUAGE*,
    PRICE*,
    PRODUCT*,
    PRODUCT_2_AWARD*,
    PRODUCT_2_CATEGORY*,
    PRODUCT_2_COUNTRY*,
    PRODUCT_2_KIT*,
    sysdiagrams*)>

<!ELEMENT ACCESSORY EMPTY>
<!ATTLIST ACCESSORY
    ACCESSORY_ID CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    WWA_DATE CDATA #REQUIRED
    LIVE_DATE CDATA #IMPLIED
>

<!ELEMENT ACCESSORY_2_AWARD EMPTY>
<!ATTLIST ACCESSORY_2_AWARD
    ACCESSORY_ID CDATA #REQUIRED
    AWARD_ID CDATA #REQUIRED
    COUNTRY_CODE CDATA #REQUIRED
>

<!ELEMENT ACCESSORY_2_CATEGORY EMPTY>
<!ATTLIST ACCESSORY_2_CATEGORY
    ACCESSORY_ID CDATA #REQUIRED
    CATEGORY_ID CDATA #REQUIRED
>

<!ELEMENT ACCESSORY_2_COUNTRY EMPTY>
<!ATTLIST ACCESSORY_2_COUNTRY
    ACCESSORY_ID CDATA #REQUIRED
    COUNTRY_ID CDATA #REQUIRED
>

<!ELEMENT ACCESSORY_2_KIT EMPTY>
<!ATTLIST ACCESSORY_2_KIT
    ACCESSORY_ID CDATA #REQUIRED
    KIT_ID CDATA #REQUIRED
    COUNTRY_CODE CDATA #REQUIRED
>

<!ELEMENT ACCESSORY_2_PRODUCT EMPTY>
<!ATTLIST ACCESSORY_2_PRODUCT
    ACCESSORY_ID CDATA #REQUIRED
    PRODUCT_ID CDATA #REQUIRED
    COUNTRY_CODE CDATA #REQUIRED
    INCLUDED CDATA #REQUIRED
>

<!ELEMENT AWARD EMPTY>
<!ATTLIST AWARD
    AWARD_ID CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
>

<!ELEMENT AWARD_2_COUNTRY EMPTY>
<!ATTLIST AWARD_2_COUNTRY
    AWARD_ID CDATA #REQUIRED
    COUNTRY_ID CDATA #REQUIRED
>

<!ELEMENT BILL_OF_MATERIALS EMPTY>
<!ATTLIST BILL_OF_MATERIALS
    BOM_ID CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    ACCESSORY_ID CDATA #IMPLIED
    PRODUCT_ID CDATA #IMPLIED
>

<!ELEMENT CATEGORY EMPTY>
<!ATTLIST CATEGORY
    CATEGORY_ID CDATA #REQUIRED
    CATEGORY_NAME CDATA #REQUIRED
    CATEGORY_DESCRIPTION CDATA #REQUIRED
    CATEGORY_LEVEL CDATA #REQUIRED
    PARENT_CATEGORY_ID CDATA #IMPLIED
>

<!ELEMENT COLOUR_WAY EMPTY>
<!ATTLIST COLOUR_WAY
    COL_WAY_ID CDATA #REQUIRED
    COLOUR CDATA #REQUIRED
    PRODUCT_ID CDATA #IMPLIED
>

<!ELEMENT COUNTRY EMPTY>
<!ATTLIST COUNTRY
    COUNTRY_ID CDATA #REQUIRED
    COUNTRY_NAME CDATA #REQUIRED
    COUNTRY_CODE CDATA #REQUIRED
    COUNTRY_CURR_NAME CDATA #REQUIRED
    COUNTRY_CURR_SYMBOL CDATA #REQUIRED
>

<!ELEMENT COUNTRY_LANGUAGE EMPTY>
<!ATTLIST COUNTRY_LANGUAGE
    COUNTRY_ID CDATA #REQUIRED
    LANGUAGE_ID CDATA #REQUIRED
>

<!ELEMENT DCR EMPTY>
<!ATTLIST DCR
    DCR_ID CDATA #REQUIRED
    LOCATION CDATA #REQUIRED
    CATEGORY_ID CDATA #IMPLIED
    PRODUCT_ID CDATA #IMPLIED
    ACCESSORY_ID CDATA #IMPLIED
    KIT_ID CDATA #IMPLIED
>

<!ELEMENT IMAGE EMPTY>
<!ATTLIST IMAGE
    IMAGE_ID CDATA #REQUIRED
    LOCATION CDATA #REQUIRED
    KIT_ID CDATA #IMPLIED
    PRODUCT_ID CDATA #IMPLIED
    ACCESSORY_ID CDATA #IMPLIED
    AWARD_ID CDATA #IMPLIED
    COL_WAY_ID CDATA #IMPLIED
>

<!ELEMENT KIT EMPTY>
<!ATTLIST KIT
    KIT_ID CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    WWA_DATE CDATA #REQUIRED
    LIVE_DATE CDATA #IMPLIED
>

<!ELEMENT KIT_2_AWARD EMPTY>
<!ATTLIST KIT_2_AWARD
    KIT_ID CDATA #REQUIRED
    AWARD_ID CDATA #REQUIRED
    COUNTRY_CODE CDATA #REQUIRED
>

<!ELEMENT KIT_2_CATEGORY EMPTY>
<!ATTLIST KIT_2_CATEGORY
    KIT_ID CDATA #REQUIRED
    CATEGORY_ID CDATA #REQUIRED
>

<!ELEMENT KIT_2_COUNTRY EMPTY>
<!ATTLIST KIT_2_COUNTRY
    KIT_ID CDATA #REQUIRED
    COUNTRY_ID CDATA #REQUIRED
>

<!ELEMENT LANGUAGE EMPTY>
<!ATTLIST LANGUAGE
    LANGUAGE_ID CDATA #REQUIRED
    LANGUAGE_NAME CDATA #REQUIRED
    LANGUAGE_CODE CDATA #REQUIRED
>

<!ELEMENT PRICE EMPTY>
<!ATTLIST PRICE
    PRICE_ID CDATA #REQUIRED
    AMOUNT CDATA #IMPLIED
    PRODUCT_ID CDATA #IMPLIED
    KIT_ID CDATA #IMPLIED
    ACCESSORY_ID CDATA #IMPLIED
    COUNTRY_ID CDATA #IMPLIED
>

<!ELEMENT PRODUCT EMPTY>
<!ATTLIST PRODUCT
    PRODUCT_ID CDATA #REQUIRED
    Q_CODE CDATA #IMPLIED
    DESCRIPTION CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    WWA_DATE CDATA #REQUIRED
    LIVE_DATE CDATA #IMPLIED
>

<!ELEMENT PRODUCT_2_AWARD EMPTY>
<!ATTLIST PRODUCT_2_AWARD
    PRODUCT_ID CDATA #REQUIRED
    AWARD_ID CDATA #REQUIRED
    COUNTRY_CODE CDATA #REQUIRED
>

<!ELEMENT PRODUCT_2_CATEGORY EMPTY>
<!ATTLIST PRODUCT_2_CATEGORY
    PRODUCT_ID CDATA #REQUIRED
    CATEGORY_ID CDATA #REQUIRED
>

<!ELEMENT PRODUCT_2_COUNTRY EMPTY>
<!ATTLIST PRODUCT_2_COUNTRY
    PRODUCT_ID CDATA #REQUIRED
    COUNTRY_ID CDATA #REQUIRED
    LEFT_NAV_SEQ CDATA #IMPLIED
>

<!ELEMENT PRODUCT_2_KIT EMPTY>
<!ATTLIST PRODUCT_2_KIT
    PRODUCT_ID CDATA #REQUIRED
    KIT_ID CDATA #REQUIRED
    COUNTRY_CODE CDATA #REQUIRED
>

<!ELEMENT sysdiagrams EMPTY>
<!ATTLIST sysdiagrams
    name CDATA #REQUIRED
    principal_id CDATA #REQUIRED
    diagram_id CDATA #REQUIRED
    version CDATA #IMPLIED
    definition CDATA #IMPLIED
>

=== stming/nics-teamsite/TeamSite/classes/src/dbunit/Nikon-BV-DBSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "./Nikon-BV-DBSchema.dtd">
<dataset>

<COUNTRY COUNTRY_ID="CNT_1" COUNTRY_NAME="GREAT BRITAIN" COUNTRY_CODE="GB"  COUNTRY_CURR_NAME="GBP" COUNTRY_CURR_SYMBOL="GBP" />
<COUNTRY COUNTRY_ID="CNT_10" COUNTRY_NAME="SWITZERLAND" COUNTRY_CODE="CH"  COUNTRY_CURR_NAME="Franc" COUNTRY_CURR_SYMBOL="CHF" />

<LANGUAGE LANGUAGE_ID="LANG_1" LANGUAGE_NAME="English" LANGUAGE_CODE="en"/>
<LANGUAGE LANGUAGE_ID="LANG_2" LANGUAGE_NAME="German" LANGUAGE_CODE="de"/>
<LANGUAGE LANGUAGE_ID="LANG_3" LANGUAGE_NAME="French" LANGUAGE_CODE="fr"/>
<LANGUAGE LANGUAGE_ID="LANG_4" LANGUAGE_NAME="Italian" LANGUAGE_CODE="it"/>

<COUNTRY_LANGUAGE COUNTRY_ID="CNT_1" LANGUAGE_ID="LANG_1" />
<COUNTRY_LANGUAGE COUNTRY_ID="CNT_10" LANGUAGE_ID="LANG_2"/>
<COUNTRY_LANGUAGE COUNTRY_ID="CNT_10" LANGUAGE_ID="LANG_3"/>
<COUNTRY_LANGUAGE COUNTRY_ID="CNT_10" LANGUAGE_ID="LANG_4"/>

<CATEGORY CATEGORY_ID="CAT_1" CATEGORY_LEVEL="1" CATEGORY_NAME="Digital Cameras" CATEGORY_DESCRIPTION="Digital Cameras"/>
<CATEGORY CATEGORY_ID="CAT_1_1" CATEGORY_LEVEL="2" CATEGORY_NAME="SLR" CATEGORY_DESCRIPTION="SLR" PARENT_CATEGORY_ID="CAT_1"/>
<CATEGORY CATEGORY_ID="CAT_1_1_1" CATEGORY_LEVEL="3" CATEGORY_NAME="Professional" CATEGORY_DESCRIPTION="Professional" PARENT_CATEGORY_ID="CAT_1_1"/>
<CATEGORY CATEGORY_ID="CAT_1_1_2" CATEGORY_LEVEL="3" CATEGORY_NAME="Consumer" CATEGORY_DESCRIPTION="Consumer" PARENT_CATEGORY_ID="CAT_1_1"/>
<CATEGORY CATEGORY_ID="CAT_1_2" CATEGORY_LEVEL="2" CATEGORY_NAME="COOLPIX" CATEGORY_DESCRIPTION="COOLPIX" PARENT_CATEGORY_ID="CAT_1"/>
<CATEGORY CATEGORY_ID="CAT_1_2_1" CATEGORY_LEVEL="3" CATEGORY_NAME="Performance" CATEGORY_DESCRIPTION="Performance" PARENT_CATEGORY_ID="CAT_1_2"/>
<CATEGORY CATEGORY_ID="CAT_1_2_2" CATEGORY_LEVEL="3" CATEGORY_NAME="Style" CATEGORY_DESCRIPTION="Style" PARENT_CATEGORY_ID="CAT_1_2"/>
<CATEGORY CATEGORY_ID="CAT_1_2_3" CATEGORY_LEVEL="3" CATEGORY_NAME="Life" CATEGORY_DESCRIPTION="Life" PARENT_CATEGORY_ID="CAT_1_2"/>

<PRODUCT PRODUCT_ID="PRD_1" DESCRIPTION="D3" TYPE="DSLR" WWA_DATE="2000-11-11" LIVE_DATE="2000-11-11" /> 
<PRODUCT_2_CATEGORY PRODUCT_ID="PRD_1" CATEGORY_ID="CAT_1_1_1"/>
<PRODUCT_2_COUNTRY PRODUCT_ID="PRD_1" COUNTRY_ID="CNT_1" LEFT_NAV_SEQ="1"/>
<PRODUCT_2_COUNTRY PRODUCT_ID="PRD_1" COUNTRY_ID="CNT_10" LEFT_NAV_SEQ="2"/>
<PRICE PRICE_ID="PR_1" PRODUCT_ID="PRD_1" COUNTRY_ID="CNT_1" AMOUNT="2999.99"/>
<PRICE PRICE_ID="PR_2" PRODUCT_ID="PRD_1" COUNTRY_ID="CNT_10" AMOUNT="5000.00"/>
<DCR DCR_ID="DCR_1" PRODUCT_ID="PRD_1" LOCATION="/product/dslr/D3.data" />

<PRODUCT PRODUCT_ID="PRD_2" DESCRIPTION="D700" TYPE="DSLR" WWA_DATE="2000-11-11" LIVE_DATE="2000-11-11" /> 
<PRODUCT_2_CATEGORY PRODUCT_ID="PRD_2" CATEGORY_ID="CAT_1_1_1"/>
<PRODUCT_2_COUNTRY PRODUCT_ID="PRD_2" COUNTRY_ID="CNT_1" LEFT_NAV_SEQ="2"/>
<PRODUCT_2_COUNTRY PRODUCT_ID="PRD_2" COUNTRY_ID="CNT_10" LEFT_NAV_SEQ="1"/>
<PRICE PRICE_ID="PR_3" PRODUCT_ID="PRD_2" COUNTRY_ID="CNT_1" AMOUNT="2000.00"/>
<PRICE PRICE_ID="PR_11" PRODUCT_ID="PRD_2" COUNTRY_ID="CNT_10" AMOUNT="4000.00"/>
<DCR DCR_ID="DCR_2" PRODUCT_ID="PRD_2" LOCATION="/product/dslr/D700.data" />

<PRODUCT PRODUCT_ID="PRD_3" DESCRIPTION="D90" TYPE="DSLR" WWA_DATE="2000-11-11" LIVE_DATE="2000-11-11" /> 
<PRODUCT_2_CATEGORY PRODUCT_ID="PRD_3" CATEGORY_ID="CAT_1_1_2"/>
<PRODUCT_2_COUNTRY PRODUCT_ID="PRD_3" COUNTRY_ID="CNT_10" LEFT_NAV_SEQ="1"/>
<PRICE PRICE_ID="PR_4" PRODUCT_ID="PRD_3" COUNTRY_ID="CNT_10" AMOUNT="3000.00"/>
<DCR DCR_ID="DCR_3" PRODUCT_ID="PRD_3" LOCATION="/product/dslr/D90.data" />

<ACCESSORY ACCESSORY_ID="ACC_1" DESCRIPTION="SB800" TYPE="FLASH" WWA_DATE="2000-11-11" LIVE_DATE="2000-11-11"/>
<ACCESSORY_2_COUNTRY ACCESSORY_ID="ACC_1" COUNTRY_ID="CNT_10"/>
<ACCESSORY_2_PRODUCT ACCESSORY_ID="ACC_1" PRODUCT_ID="PRD_1" COUNTRY_CODE="CH" INCLUDED="0"/>
<ACCESSORY_2_PRODUCT ACCESSORY_ID="ACC_1" PRODUCT_ID="PRD_2" COUNTRY_CODE="CH" INCLUDED="1"/>
<PRICE PRICE_ID="PR_5" ACCESSORY_ID="ACC_1" COUNTRY_ID="CNT_1" AMOUNT="100"/>
<PRICE PRICE_ID="PR_6" ACCESSORY_ID="ACC_1" COUNTRY_ID="CNT_10" AMOUNT="1000"/>
<DCR DCR_ID="DCR_4" ACCESSORY_ID="ACC_1" LOCATION="/accessories/dslr/SB800.data" />

<ACCESSORY ACCESSORY_ID="ACC_2" DESCRIPTION="HD Cable" TYPE="Cable" WWA_DATE="2000-11-11" LIVE_DATE="2000-11-11"/>
<ACCESSORY_2_COUNTRY ACCESSORY_ID="ACC_2" COUNTRY_ID="CNT_10"/>
<ACCESSORY_2_PRODUCT ACCESSORY_ID="ACC_2" PRODUCT_ID="PRD_3" COUNTRY_CODE="CH" INCLUDED="1"/>
<PRICE PRICE_ID="PR_7" ACCESSORY_ID="ACC_2" COUNTRY_ID="CNT_1" AMOUNT="200"/>
<PRICE PRICE_ID="PR_8" ACCESSORY_ID="ACC_2" COUNTRY_ID="CNT_10" AMOUNT="2000"/>
<DCR DCR_ID="DCR_5" ACCESSORY_ID="ACC_2" LOCATION="/accessories/dslr/HD Cable.data" />

<ACCESSORY ACCESSORY_ID="ACC_3" DESCRIPTION="SB90" TYPE="FLASH" WWA_DATE="2009-11-11" LIVE_DATE="2009-11-11"/>
<ACCESSORY_2_COUNTRY ACCESSORY_ID="ACC_3" COUNTRY_ID="CNT_1"/>
<ACCESSORY_2_COUNTRY ACCESSORY_ID="ACC_3" COUNTRY_ID="CNT_10"/>
<ACCESSORY_2_PRODUCT ACCESSORY_ID="ACC_3" PRODUCT_ID="PRD_1" COUNTRY_CODE="GB" INCLUDED="0"/>
<ACCESSORY_2_PRODUCT ACCESSORY_ID="ACC_3" PRODUCT_ID="PRD_1" COUNTRY_CODE="CH" INCLUDED="1"/>
<PRICE PRICE_ID="PR_9" ACCESSORY_ID="ACC_3" COUNTRY_ID="CNT_1" AMOUNT="300"/>
<PRICE PRICE_ID="PR_10" ACCESSORY_ID="ACC_3" COUNTRY_ID="CNT_10" AMOUNT="3000"/>
<DCR DCR_ID="DCR_6" ACCESSORY_ID="ACC_3" LOCATION="/accessories/dslr/SB90.data" />

</dataset>
